import { Field, ObjectType } from '@nestjs/graphql';
import { ROLES } from '../enums/roles.enum';

@ObjectType()
export class Profile {
  @Field({ description: 'value generated by mongoDb' })
  id: string;

  @Field()
  userId: string;

  @Field(() => String)
  role: ROLES;

  @Field()
  firstName: string;

  @Field()
  lastName: string;

  @Field()
  birthDay: string;

  @Field()
  city: string;

  @Field()
  tel: string;

  @Field()
  profileImg: string;
}
